import { EventData } from "src/app/shared/models/event.model";

export const eventData: EventData[] = [
  {
     eventDay: "Sunday",
    imageSrc: "https://files.fm/thumb_show.php?i=3wzunbjta",
    imageAlt: "Reso Kiknadze Quartet",
    bandName: "Reso Kiknade Quartet",
    members: [
      "Reso Kiknadze",
      "Irakli Kuku Choladze",
      "Nika Gabadze",
      "Giorgi Samsonadze",
    ],
    youtubeLinks: [
      "rWaPle0GnnM",
      "0CWoFJX4iIY",
      "9UY-DmiIjjM",
      "o-Dtqlp25s4",
    ],
  },
  { eventDay: "Monday",
    imageSrc: "https://files.fm/thumb_show.php?i=x7yz2ur3s",
    imageAlt: "Gigi, Noe, Soso, Egor",
    bandName: "Gigi Tsintsadze Quartet",
    members: ["Gigi Tsintsadze", "Noe Gabashvili", "Soso Tsagareishvili", "Egor Popov",],
    youtubeLinks: [
      "Zu5Di5ezZJk",
      "u4hBrq9qudY",
      "qhvoG6nQG9M",
      "VG_6QzQgs1M",
    ],
  },
  { eventDay: "Tuesday",
    imageSrc: "https://files.fm/thumb_show.php?i=cfquwdyxq",
    imageAlt: "Kakha, Irakli, Nika, Khatia",
    bandName: "Kakha Jagashvili Quartet",
    members: ["Kakha Jagashvili", "Irakli Choladze", "Khatia Koridze", "Nika Gabadze"],
    youtubeLinks: [""],
  },
  { eventDay: "Wednesday",
    imageSrc: "https://files.fm/thumb_show.php?i=srkz9z29h",
    imageAlt: "Luka, Khatia, Tornike, Lasha, Gio",
    bandName: "Luka Topuria Quintet",
    members: ["Luka Topuria", "Gio Kapanadze", "Khatia Koridze", "Lasha Deisadze", "Tornike Abuladze", ],
    youtubeLinks: [
      "Xp5YTD5uehc",
      "_ZXB7zKGzWc",
      "DfoEMVKVZHM",
      "4EposNjHr8A",
      "yyl8zPWyKGc",
    ],

  },
  { eventDay: "Thursday",
    imageSrc: "https://files.fm/thumb_show.php?i=h434nrrnw",
    imageAlt: "Gia Rakviashvili, Giorgi Samsonadze, Giorgi Melikishvili",
    bandName: "New York Tbilisi Connection",
    members: ["Gia Rakviashvili", "Giorgi Samsonadze", "George Melikishvili"],
    youtubeLinks: ["woOna1JCXJE", "L5LqMJURCfE"],
  },
  { eventDay: "Friday",
    imageSrc: "https://files.fm/thumb_show.php?i=fb6ar77q7",
    imageAlt: "Daniel Adikashvili, Ucha Metreveli, Levan Lortkipanidze, Giorgi Samsonadze",
    bandName: "Blues Night",
    members: ["Daniel Adikashvili", "Ucha Metreveli", "Levan Lortkipanidze", "Giorgi Samsonadze"],
    youtubeLinks: [""],
  },
  { eventDay: "Saturday",
    imageSrc: "https://files.fm/thumb_show.php?i=s4h9v7b3d",
    imageAlt: "Gia Rakviashvili, Giorgi Samsonadze, Giorgi Melikishvili",
    bandName: "Luka Topuria Quartet",
    members: ["Luka Topuria", "Daniel Adikashvili", "Lasha Deisadze", "Khatia Koridze", ],
    youtubeLinks: [
      "Xp5YTD5uehc",
      "_ZXB7zKGzWc",
      "DfoEMVKVZHM",
      "4EposNjHr8A",
      "yyl8zPWyKGc",
    ],
  },
]



